### ISSUE TITLE
Connection status code

### ISSUE THREAD

**Issue by shaharmor** [whatwg/websockets#21]
Hey,

Following this: https://bugs.chromium.org/p/chromium/issues/detail?id=695932#c3

I think its important to expose somehow the HTTP status code from the initial handshake of the WebSocket connection to user-land JS to be able to differentiate between different cases such as invalid authentication, rate-limiting, etc.

**Comment by ricea** [comment]
The fact that different types of errors are indistinguishable from JavaScript is an intentional feature of the WebSocket API to prevent it from being used for port scans and other attacks.

If at some point we implement CORS for WebSockets then that might change (but then you'd have to deal with CORS errors instead, so your life definitely wouldn't get easier).
